# Sentiment Classification


### Generate Word Embeddings and retrieve outputs of each layer with Keras based on Classification task

Word embeddings are a type of word representation that allows words with similar meaning to have a similar representation.

It is a distributed representation for text that is perhaps one of the key breakthroughs for the impressive performance of deep learning methods on challenging natural language processing problems.

We willl use the imdb dataset to learn word embeddings as we train our dataset. This dataset contains 25,000 movie reviews from IMDB, labeled with sentiment (positive or negative). 



### Dataset

`from keras.datasets import imdb`

Dataset of 25,000 movies reviews from IMDB, labeled by sentiment (positive/negative). Reviews have been preprocessed, and each review is encoded as a sequence of word indexes (integers). For convenience, the words are indexed by their frequency in the dataset, meaning the for that has index 1 is the most frequent word. Use the first 20 words from each review to speed up training, using a max vocab size of 10,000.

As a convention, "0" does not stand for a specific word, but instead is used to encode any unknown word.


### Aim

1. Import test and train data  
2. Import the labels ( train and test) 
3. Get the word index and then Create key value pair for word and word_id. (12.5 points)
4. Build a Sequential Model using Keras for Sentiment Classification task. (10 points)
5. Report the Accuracy of the model. (5 points)  
6. Retrive the output of each layer in keras for a given single test sample from the trained model you built. (2.5 points)


#### Usage:

In [0]:
#1.Import test and train data

In [2]:
!pip install numpy==1.16.2
import numpy as np

In [3]:
from keras.datasets import imdb

vocab_size = 10000 #vocab size

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size) # vocab_size is no.of words to consider from the dataset, ordering based on frequency.

Using TensorFlow backend.


In [0]:
from keras.preprocessing.sequence import pad_sequences
vocab_size = 10000 #vocab size
maxlen = 300  #number of word used from each review

In [0]:
#2. Import the labels ( train and test)

In [0]:
#load dataset as a list of ints
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size)
#make all sequences of the same length
x_train = pad_sequences(x_train, maxlen=maxlen)
x_test =  pad_sequences(x_test, maxlen=maxlen)

In [7]:
print ("x_train shape: ", x_train.shape)
print ("y_train shape: ", y_train.shape)
print ("x_test shape: ", x_test.shape)
print ("y_test shape: ", y_test.shape)

('x_train shape: ', (25000, 300))
('y_train shape: ', (25000,))
('x_test shape: ', (25000, 300))
('y_test shape: ', (25000,))


In [8]:
print("Maximum value of a word index ")
print(max([max(sequence) for sequence in x_train]))
print("Maximum length num words of review in train ")
print(max([len(sequence) for sequence in x_train]))

Maximum value of a word index 
9999
Maximum length num words of review in train 
300


In [0]:
#3.Get the word index and then Create key value pair for word and word_id. (12.5 points)

In [0]:
# Make Word to ID dictionary
INDEX_FROM=3   # word index offset
word_to_id = imdb.get_word_index() #Get the word index
word_to_id = {k:(v+INDEX_FROM) for k,v in word_to_id.items()}

word_to_id["<PAD>"] = 0

word_to_id["<START>"] = 1

word_to_id["<UNK>"] = 2

# Make ID to Word dictionary
id_to_word = {value:key for key,value in word_to_id.items()}

def restore_original_text(imdb_x_array):
    return (' '.join(id_to_word[id] for id in imdb_x_array ))


In [11]:
id_to_word

{0: '<PAD>',
 1: '<START>',
 2: '<UNK>',
 4: u'the',
 5: u'and',
 6: u'a',
 7: u'of',
 8: u'to',
 9: u'is',
 10: u'br',
 11: u'in',
 12: u'it',
 13: u'i',
 14: u'this',
 15: u'that',
 16: u'was',
 17: u'as',
 18: u'for',
 19: u'with',
 20: u'movie',
 21: u'but',
 22: u'film',
 23: u'on',
 24: u'not',
 25: u'you',
 26: u'are',
 27: u'his',
 28: u'have',
 29: u'he',
 30: u'be',
 31: u'one',
 32: u'all',
 33: u'at',
 34: u'by',
 35: u'an',
 36: u'they',
 37: u'who',
 38: u'so',
 39: u'from',
 40: u'like',
 41: u'her',
 42: u'or',
 43: u'just',
 44: u'about',
 45: u"it's",
 46: u'out',
 47: u'has',
 48: u'if',
 49: u'some',
 50: u'there',
 51: u'what',
 52: u'good',
 53: u'more',
 54: u'when',
 55: u'very',
 56: u'up',
 57: u'no',
 58: u'time',
 59: u'she',
 60: u'even',
 61: u'my',
 62: u'would',
 63: u'which',
 64: u'only',
 65: u'story',
 66: u'really',
 67: u'see',
 68: u'their',
 69: u'had',
 70: u'can',
 71: u'were',
 72: u'me',
 73: u'well',
 74: u'than',
 75: u'we',
 76: u'much',
 

In [12]:
#Lets Decode and check for some train values.
x_train[10]

array([   6,  346,  137,   11,    4, 2768,  295,   36, 7740,  725,    6,
       3208,  273,   11,    4, 1513,   15, 1367,   35,  154,    2,  103,
          2,  173,    7,   12,   36,  515, 3547,   94, 2547, 1722,    5,
       3547,   36,  203,   30,  502,    8,  361,   12,    8,  989,  143,
          4, 1172, 3404,   10,   10,  328, 1236,    9,    6,   55,  221,
       2989,    5,  146,  165,  179,  770,   15,   50,  713,   53,  108,
        448,   23,   12,   17,  225,   38,   76, 4397,   18,  183,    8,
         81,   19,   12,   45, 1257,    8,  135,   15,    2,  166,    4,
        118,    7,   45,    2,   17,  466,   45,    2,    4,   22,  115,
        165,  764, 6075,    5, 1030,    8, 2973,   73,  469,  167, 2127,
          2, 1568,    6,   87,  841,   18,    4,   22,    4,  192,   15,
         91,    7,   12,  304,  273, 1004,    4, 1375, 1172, 2768,    2,
         15,    4,   22,  764,   55, 5773,    5,   14, 4233, 7444,    4,
       1375,  326,    7,    4, 4760, 1786,    8,  3

In [13]:
restore_original_text(x_train[10])

u"a short while in the cell together they stumble upon a hiding place in the wall that contains an old <UNK> after <UNK> part of it they soon realise its magical powers and realise they may be able to use it to break through the prison walls br br black magic is a very interesting topic and i'm actually quite surprised that there aren't more films based on it as there's so much scope for things to do with it it's fair to say that <UNK> makes the best of it's <UNK> as despite it's <UNK> the film never actually feels restrained and manages to flow well throughout director eric <UNK> provides a great atmosphere for the film the fact that most of it takes place inside the central prison cell <UNK> that the film feels very claustrophobic and this immensely benefits the central idea of the prisoners wanting to use magic to break out of the cell it's very easy to get behind them it's often said that the unknown is the thing that really <UNK> people and this film proves that as the director <U

In [14]:
#Lets Decode and check for some test values.
x_test[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [15]:
restore_original_text(x_test[0])

u"<PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <P

## Build Keras Embedding Layer Model
We can think of the Embedding layer as a dicionary that maps a index assigned to a word to a word vector. This layer is very flexible and can be used in a few ways:

* The embedding layer can be used at the start of a larger deep learning model. 
* Also we could load pre-train word embeddings into the embedding layer when we create our model.
* Use the embedding layer to train our own word2vec models.

The keras embedding layer doesn't require us to onehot encode our words, instead we have to give each word a unqiue intger number as an id. For the imdb dataset we've loaded this has already been done, but if this wasn't the case we could use sklearn [LabelEncoder](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html).

In [0]:
#4.Build a Sequential Model using Keras for Sentiment Classification task. (10 points)

In [17]:
import tensorflow as tf
from tensorflow import keras
from keras import backend as K
import numpy as np
#from keras.layers import LSTM, Dense, Dropout, Embedding, Masking, Bidirectional, GlobalAveragePooling1D

tf.set_random_seed(100)

model = keras.Sequential()
model.add(keras.layers.Embedding(vocab_size, 16))
model.add(keras.layers.GlobalAveragePooling1D())
model.add(keras.layers.Dense(64, activation='relu'))

# Dropout for regularization
model.add(keras.layers.Dropout(0.5))
model.add(keras.layers.Dense(32, activation="relu"))
model.add(keras.layers.Dense(16, activation="relu"))
model.add(keras.layers.Dense(1, activation="sigmoid"))


W0308 09:50:23.652095 140235238573952 deprecation.py:506] From /usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/initializers.py:119: calling __init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0308 09:50:23.677509 140235238573952 deprecation.py:506] From /usr/local/lib/python2.7/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling __init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 16)          160000    
_________________________________________________________________
global_average_pooling1d (Gl (None, 16)                0         
_________________________________________________________________
dense (Dense)                (None, 64)                1088      
_________________________________________________________________
dropout (Dropout)            (None, 64)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_2 (Dense)              (None, 16)                528       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 1

In [19]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['acc'])

W0308 09:50:23.794552 140235238573952 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow_core/python/ops/nn_impl.py:183: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [20]:
history = model.fit(x_train,
                    y_train,
                    epochs=20,
                    batch_size=512,
                    validation_data=(x_test, y_test),
                    verbose=1)

Train on 25000 samples, validate on 25000 samples
Epoch 1/20
25000/25000 [==============================] - 1s 34us/sample - loss: 0.6913 - acc: 0.5565 - val_loss: 0.6826 - val_acc: 0.6524
Epoch 2/20
25000/25000 [==============================] - 1s 21us/sample - loss: 0.6145 - acc: 0.7559 - val_loss: 0.4884 - val_acc: 0.8256
Epoch 3/20
25000/25000 [==============================] - 1s 20us/sample - loss: 0.3777 - acc: 0.8562 - val_loss: 0.3237 - val_acc: 0.8683
Epoch 4/20
25000/25000 [==============================] - 1s 20us/sample - loss: 0.2669 - acc: 0.8996 - val_loss: 0.3019 - val_acc: 0.8763
Epoch 5/20
25000/25000 [==============================] - 1s 20us/sample - loss: 0.2187 - acc: 0.9202 - val_loss: 0.2963 - val_acc: 0.8809
Epoch 6/20
25000/25000 [==============================] - 1s 21us/sample - loss: 0.1857 - acc: 0.9358 - val_loss: 0.3027 - val_acc: 0.8808
Epoch 7/20
25000/25000 [==============================] - 1s 20us/sample - loss: 0.1632 - acc: 0.9471 - val_loss: 0.

In [0]:
#5.Report the Accuracy of the model. (5 points)

In [22]:
print('\nModel Performance: Log Loss and Accuracy on train data')
print(model.evaluate(x_train, y_train, batch_size = 20))
print('\nModel Performance: Log Loss and Accuracy on validation data')
print(model.evaluate(x_test, y_test, batch_size = 20))


Model Performance: Log Loss and Accuracy on train data
25000/25000 [==============================] - 2s 66us/sample - loss: 0.0348 - acc: 0.9942
[0.034775503547303376, 0.99416]

Model Performance: Log Loss and Accuracy on validation data
25000/25000 [==============================] - 2s 67us/sample - loss: 0.5787 - acc: 0.8558
[0.5787091667998582, 0.85584]


In [23]:
'''
PREDICT
'''
import random
import pandas as pd

original_x_test = x_test

def restore_original_text(imdb_x_array):
    return (' '.join(id_to_word[id] for id in imdb_x_array ))

def imdb_class_to_str(imdb_class):
    if imdb_class == 0:
        return 'negative'
    return 'positive'

right = 0
mistake = 0

index_list = []
original_text_list = []
pred_prob_list = []
pred_class_list = []
y_test_list = []
fail_str_list = []

for i in range(100):
    index = random.randint(0, len(x_test))
    
    pred_prob = model.predict(x_test[index:(index+1)])[0][0] 
    pred_class = model.predict_classes(x_test[index:(index+1)])[0][0]
    
    '''
    print('pred_prod:', pred_prod)
    print('pred_class:', pred_class)
    print('y_test[index] :', y_test[index])
    '''
    fail_str = '' 
    
    if y_test[index] == pred_class:
        right += 1
    else:
        mistake += 1
        fail_str = 'Fail'
        
    original_text = restore_original_text(original_x_test[index])

    index_list.append(index)
    original_text_list.append(original_text)
    pred_prob_list.append(pred_prob)
    pred_class_list.append(imdb_class_to_str(pred_class))
    y_test_list.append(imdb_class_to_str(y_test[index]))
    fail_str_list.append(fail_str)

print("right : ", right)
print("mistake : ", mistake)

df = pd.DataFrame({'index': index_list, 
                   'x_test_original_text': original_text_list, 
                   'probability': pred_prob_list, 
                   'pred_class': pred_class_list,
                   'y_test': y_test_list,
                   'is_fail': fail_str_list
                  })

df[['index', 'x_test_original_text','probability','pred_class','y_test','is_fail']]

('right : ', 89)
('mistake : ', 11)


index                               x_test_original_text  ...    y_test is_fail
0   20710  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  negative        
1   11779  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  negative        
2    6149  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  negative        
3   21575  to pointless arty detail the important matters...  ...  negative        
4    5802  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  negative        
5    8751  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  negative        
6   17117  each other <UNK> <UNK> as they become increasi...  ...  positive        
7    2926  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  negative        
8     957  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  positive        
9   14346  men looked handsome and <UNK> br br is this a ...  ...  negative    Fail
10  15513  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  positive        
11  15207  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <START> <U...  ...  negative        
12  17913  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  negative        
13  17651  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  negative        
14  17408  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  positive        
15   5759  cinematography <UNK> nut is one for the ages a...  ...  positive        
16    983  before leaving to montana when they stopped at...  ...  negative    Fail
17   6334  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  positive        
18  17483  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  positive        
19  10430  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  negative        
20  18843  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  positive        
21  16257  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  positive        
22  22105  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  positive        
23   1366  i found this movie on a <UNK> sale <UNK> for 3...  ...  negative        
24  10896  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  negative        
25  19878  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  negative        
26  16490  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  positive        
27  15494  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  positive        
28   3053  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  positive        
29   1542  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <STA...  ...  negative        
..    ...                                                ...  ...       ...     ...
70  24155  <UNK> remake we were almost unable to keep fro...  ...  positive    Fail
71  23495  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  negative        
72  17472  mute witness starring a cast of <UNK> except a...  ...  positive    Fail
73   3973  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  positive        
74  10926  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  negative        
75   4448  a script that never really delivers the amount...  ...  negative        
76   6768  into that nasty series post alien 3 habit of <...  ...  negative        
77  21264  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  positive        
78   9696  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  negative        
79  11456  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  positive        
80   5548  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  negative        
81   6790  how badly they'd got me on this one this is a ...  ...  negative        
82  22056  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  positive        
83   9228  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  positive    Fail
84  22792  <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD...  ...  positive        
85   6677  of the swamp making it at times far more scar

## Retrive the output of each layer in keras for a given single test sample from the trained model you built

In [0]:
#6.Retrive the output of each layer in keras for a given single test sample from the trained model you built. (2.5 points)

In [0]:
from keras import backend as k

In [26]:
#Define function to get output of all the layers in the model for specific test input
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.tables_initializer())

    def getLayerOutput(layer):
        get_Layer_Output = k.function([model.layers[0].input], [layer.output])
        return get_Layer_Output([x_test[0:1,]])[0]
    
    layer_output = []
    
    for layer in model.layers:
        layer_output.append(getLayerOutput(layer))

W0308 09:54:35.226464 140235238573952 module_wrapper.py:139] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0308 09:54:35.227505 140235238573952 module_wrapper.py:139] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:190: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.



In [27]:
#Get the count of ouput. It should be equal to the number of layers
len(layer_output)

7

In [28]:
#Check all the outputs
layer_output

[array([[[-0.00458338,  0.04823485,  0.02042371, ...,  0.03888449,
          -0.01751048,  0.00803411],
         [-0.00458338,  0.04823485,  0.02042371, ...,  0.03888449,
          -0.01751048,  0.00803411],
         [-0.00458338,  0.04823485,  0.02042371, ...,  0.03888449,
          -0.01751048,  0.00803411],
         ...,
         [ 0.04579827, -0.00981784, -0.02570111, ...,  0.02962463,
          -0.04944974, -0.02211731],
         [ 0.04799093, -0.03852631,  0.04156684, ..., -0.01586529,
          -0.03594899,  0.03170117],
         [-0.00144356,  0.04378692,  0.00424818, ..., -0.01755618,
          -0.0028383 , -0.03627374]]], dtype=float32),
 array([[-0.00301607,  0.03692188,  0.01417997, -0.01547567, -0.01877829,
          0.0399677 , -0.0034747 , -0.01725606,  0.0074258 , -0.00178651,
          0.01001158, -0.00320485, -0.02594487,  0.0301198 , -0.01571364,
          0.00830047]], dtype=float32),
 array([[0.        , 0.        , 0.01101602, 0.00524644, 0.        ,
         0.  

In [29]:
#Get the specific layer output
layer_output[2]

array([[0.        , 0.        , 0.01101602, 0.00524644, 0.        ,
        0.        , 0.        , 0.01019217, 0.        , 0.        ,
        0.01768403, 0.01140995, 0.        , 0.00893559, 0.00641206,
        0.01021314, 0.        , 0.00821325, 0.        , 0.0034901 ,
        0.        , 0.        , 0.        , 0.02163267, 0.00107495,
        0.        , 0.02565341, 0.02123948, 0.02182533, 0.00820519,
        0.00686321, 0.00561919, 0.        , 0.        , 0.        ,
        0.0016309 , 0.        , 0.        , 0.00802844, 0.        ,
        0.00860214, 0.        , 0.0046777 , 0.011356  , 0.02129352,
        0.01169974, 0.00418537, 0.        , 0.        , 0.00566915,
        0.        , 0.00548731, 0.00245883, 0.00457622, 0.00041493,
        0.01304827, 0.01613861, 0.00882609, 0.        , 0.        ,
        0.00266701, 0.        , 0.00302794, 0.00224574]], dtype=float32)