___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

In [1]:
import numpy as np
arr = np.arange(0,10)

In [2]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [5]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [6]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [7]:
np.max(arr) #same as arr.max()

9

In [8]:
a=np.sin(arr)
a

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [9]:
#Usage of for-loop
#Mapping by Value
for val in a:
  print(val)

0.0
0.8414709848078965
0.9092974268256817
0.1411200080598672
-0.7568024953079282
-0.9589242746631385
-0.27941549819892586
0.6569865987187891
0.9893582466233818
0.4121184852417566


In [12]:
#Mapping by index
for idx in np.arange(len(arr)):
    print(arr[idx]+100)
print("all done")

100
101
102
103
104
105
106
107
108
109
all done


In [15]:
b=[] #empty list going to collect all -ve nos
for val in a:
    if val<0:
        b.append(val)
print(b)
#b1=np.array(b)
#print(b1) get the ans in array form


[-0.7568024953079282, -0.9589242746631385, -0.27941549819892586]


In [16]:
#same task by index calling
b1=[]
for idx in np.arange(len(a)):
    if a[idx]<0:
        b1.append(a[idx])
print(b1)

[-0.7568024953079282, -0.9589242746631385, -0.27941549819892586]


In [7]:
for val in a:
  if val>0:
    print(val)

0.8414709848078965
0.9092974268256817
0.1411200080598672
0.6569865987187891
0.9893582466233818
0.4121184852417566


In [21]:
#if we have to replace all 3 negative nos by 0 it is possible only by mapping by index
for idx in np.arange(len(a)):
    if a[idx]<0:
        a[idx]=0
print(a)

[0.         0.84147098 0.90929743 0.14112001 0.         0.
 0.         0.6569866  0.98935825 0.41211849]


In [8]:
for val in a:
  if val>0:
    print(val)
  else:
    print('Negative')

Negative
0.8414709848078965
0.9092974268256817
0.1411200080598672
Negative
Negative
Negative
0.6569865987187891
0.9893582466233818
0.4121184852417566


In [10]:
for val in a:
  if val>0 and val<0.5:
    print(val)

0.1411200080598672
0.4121184852417566


In [11]:
#Mapping by Index
for i in np.arange(len(a)):
  print(a[i]+10)

10.0
10.841470984807897
10.909297426825681
10.141120008059866
9.243197504692072
9.041075725336862
9.720584501801074
10.656986598718788
10.989358246623382
10.412118485241757


In [12]:
b=[]
for i in np.arange(len(a)):
  b.append(a[i]+10)
print(b)

[10.0, 10.841470984807897, 10.909297426825681, 10.141120008059866, 9.243197504692072, 9.041075725336862, 9.720584501801074, 10.656986598718788, 10.989358246623382, 10.412118485241757]


In [0]:
#Replace the negative nos in the array into zeros

In [20]:
#We can do the above process in the form of list comprehension
out=[val+10 for val in a if val>0]
print(out)

[10.841470984807897, 10.909297426825681, 10.141120008059866, 10.656986598718788, 10.989358246623382, 10.412118485241757]


In [42]:
#2-Dimensional for-loop
b=np.array([[9,4,3],[8,5,2]])
b

array([[9, 4, 3],
       [8, 5, 2]])

In [43]:
len(b[0])

3

In [44]:
for row in np.arange(len(b)):
  print(b[row])
  print('done')

[9 4 3]
done
[8 5 2]
done


In [45]:
for row in np.arange(len(b)):
  for col in np.arange(len(b[row])):
    print(b[row,col])
    print('done')

9
done
4
done
3
done
8
done
5
done
2
done


In [46]:
out2=[b[row,col]+100 for row in np.arange(len(b)) for col in np.arange(len(b[row]))] #list comprehension for 2d for loop
out2

[109, 104, 103, 108, 105, 102]

In [87]:
b_out=np.zeros((2,3))
b_out

array([[0., 0., 0.],
       [0., 0., 0.]])

In [89]:
b

array([[9, 4, 3],
       [8, 5, 2]])

In [88]:
for row in np.arange(len(b)):                                                                                  # see from recoreded lec
    for col in np.arange(len(b[row])):
        b_out[row,col]=b[row,col]+100
print(b_out)

[[109. 104. 103.]
 [108. 105. 102.]]


In [72]:
#Usage of While Loop
k = 1
while k < 5:
    print('k is: %d'%(k))
    k = k+1

k is: 1
k is: 2
k is: 3
k is: 4


In [73]:
#User Defined Functions
def my_avg(dat):
  s=sum(dat)
  avg=s/len(dat)
  return avg,s

In [74]:
new_data=[5,3,2]
my_avg(new_data)

(3.3333333333333335, 10)

In [75]:
def times2(var):
    return var*2

In [76]:
times2(6)

12

In [77]:
#Anonymous Function
x=lambda var:var*2
print(x(20))

40


In [78]:
var=5

In [79]:
#Usage of Map and Filter
seq = [5,2,3,6,4]
list(map(times2,seq))

[10, 4, 6, 12, 8]

In [80]:
list(map(lambda var: var*2,seq))

[10, 4, 6, 12, 8]

In [81]:
list(filter(lambda item: item%2 == 0,seq))

[2, 6, 4]

In [82]:
seq

[5, 2, 3, 6, 4]

GET squares

In [1]:
x=[5,2,3,6,4]
#we want output list y=[25,4,9,36,16]


In [2]:
#option 1
y=[]
for val in x:
    y.append(val**2)
print(y)

[25, 4, 9, 36, 16]


In [3]:
#option 2
y=[val**2 for val in x]
print(y)

[25, 4, 9, 36, 16]


In [7]:
#option 3 user defined function
def my_sq(x):
    return (x**2)


In [10]:
#option 4 call this user defined function using map
y=list(map(my_sq,x))
print(y)

[25, 4, 9, 36, 16]


In [13]:
#option 5 lambda anonymous function
y=list(map(lambda val:val**2,x))
y

[25, 4, 9, 36, 16]

In [14]:
#option 6
def my_sq2(x):
    y=[]
    for val in x:
        y.append(val**2)
    return y

In [15]:
my_sq2([4,5])

[16, 25]

In [19]:
#list comprehension to get the even nos option 1
y=[val for val in x if val%2==0]
y

[2, 6, 4]

In [20]:
x=[2,5,3,8,10,7]

In [21]:
# filter method to get even nos
list(filter(lambda val: val%2 == 0,x))

[2, 8, 10]

In [34]:
y=[]
for val in x:
    if val%2==0:
        y.append(val)
print(y)
    


[2, 8, 10]
